name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!!!"

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: List files of the repositories
        run: |
          echo "The repository ${{ github.repository }} containsthe following files:"
          tree


